import type {Metadata} from "next";


import "./globals.css";
import { TopMenu } from "@/components/nav/TopMenu";

export const metadata: Metadata = {
  title: "almond_web",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background  font-figtree antialiased">
        <TopMenu/>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} almond_web
        </footer>
      </body>
    </html>
  );
}
